name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Login to Packages Container registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Spark-Operator Docker Image to github container registry
        run: |
          export DOCKER_BUILDKIT=1
          DOCKER_TAG=$(cat charts/spark-operator-chart/Chart.yaml | grep "appVersion: .*" | cut -c13-)
          docker build -t ghcr.io/teamziax/spark-operator:${DOCKER_TAG} -f Dockerfile.rh --build-arg SPARK_IMAGE=gcr.io/datamechanics/custom/spark:netapp-spark-support-image-v3.5.0-dev-amd64 .
          docker push ghcr.io/teamziax/spark-operator:${DOCKER_TAG}
